### ISSUE TITLE
Cashbill | invalid signature generator

### ISSUE THREAD

**Issue by SUGERUS** [WiktorDev/node-payments-lib2.0#1]
An incorrect signature is generated in the payment generation, I have checked this and the values to generate the signature are not in the correct order as recommended by the documentation.
![image](https://user-images.githubusercontent.com/74995616/192564859-a3f6c545-2d58-45af-8bdf-3e544047d76b.png)

**Comment by SUGERUS** [comment]
I wrote it in the wrong repo, I meant the v2 version.

**Comment by SUGERUS** [comment]
In addition, it does not return error messages, after adding the console log, it returns info about an invalid signature, after changing the order it manually starts working in the sandbox mode.

![image](https://user-images.githubusercontent.com/74995616/192619678-641263c3-7746-4929-ac81-ec9f98afbcd3.png)

**Comment by SUGERUS** [comment]
Will it be fixed?

**Comment by SUGERUS** [comment]
> An incorrect signature is generated in the payment generation, I have checked this and the values to generate the signature are not in the correct order as recommended by the documentation.
> 
> ![image](https://user-images.githubusercontent.com/74995616/192564859-a3f6c545-2d58-45af-8bdf-3e544047d76b.png)
> 
> 


This will be fixed too? Its still generating signature wrong.

**Comment by WiktorDev** [comment]
Can you send your code where you generate the payment?

**Comment by SUGERUS** [comment]
![image](https://user-images.githubusercontent.com/74995616/207883918-b68a35db-e39f-4abf-b7de-db0f92f41eb4.png)

**Comment by SUGERUS** [comment]
![image](https://user-images.githubusercontent.com/74995616/207968291-88168cba-1a65-48bc-bc3e-4269ea8c7eed.png)
I just changed generate function into this, and its working perfectly fine.
